ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "funnelStep" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "funnelDoneAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastActiveDate" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isAdmin" BOOLEAN NOT NULL DEFAULT false;

UPDATE "User"
SET "isAdmin" = true
WHERE "tgId" IN ('1113930428', '435149892');

CREATE TABLE IF NOT EXISTS "PushLog" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "type" TEXT NOT NULL,
  "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ok" BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT "PushLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "PushLog_userId_type_sentAt_key" ON "PushLog"("userId", "type", "sentAt");
CREATE INDEX IF NOT EXISTS "PushLog_userId_idx" ON "PushLog"("userId");
CREATE INDEX IF NOT EXISTS "PushLog_type_idx" ON "PushLog"("type");

CREATE TABLE IF NOT EXISTS "Broadcast" (
  "id" SERIAL PRIMARY KEY,
  "text" TEXT NOT NULL,
  "buttonLabel" TEXT,
  "buttonUrl" TEXT,
  "sentCount" INTEGER NOT NULL DEFAULT 0,
  "failCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "adminId" TEXT NOT NULL
);
